# Header (especifica la versión de la plantilla y una descripción)
AWSTemplateFormatVersion: "2010-09-09"
Description: "Characters ECR Repository for CRUD application"

# Define el nombre del repositorio ECR, con un valor por defecto
Parameters:
  RepositoryName:
    Type: String
    Default: characters-app
    Description: ECR repository name

# Define el servicio a crear (un repositorio ECR en este caso)
Resources:
  # Configuración del repositorio: nombre, escaneo de imágenes al subir y política de ciclo de vida
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${RepositoryName}-${AWS::StackName}"
      ImageScanningConfiguration:
        ScanOnPush: false
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Mantain only last 2 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

# Valores que pueden ser accedidos fuera de la pila: URI del repositorio, nombre y ARN (identificador único del repositorio)
Outputs:
  RepositoryUri:
    Description: ECR URI
    Value: !GetAtt ECRRepository.RepositoryUri

  RepositoryName:
    Description: Repository Name
    Value: !Ref RepositoryName

  RepositoryArn:
    Description: Repository ARN
    Value: !GetAtt ECRRepository.Arn