AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR Repository for Lambda Functions - CRUD Puro Desacoplado"

Parameters:
  RepositoryName:
    Type: String
    Default: characters-lambda
    Description: Base name for the ECR repository

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${RepositoryName}-${AWS::StackName}"
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: false
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 2 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: ECR URI
    Value: !GetAtt ECRRepository.RepositoryUri

  RepositoryName:
    Description: Repository Name
    Value: !Ref RepositoryName

  RepositoryArn:
    Description: Repository ARN
    Value: !GetAtt ECRRepository.Arn
    